name: Build and Release (.NET Framework)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build with MSBuild
      run: msbuild OOP-GUI2.sln /p:Configuration=Release

    - name: Archive Artifacts
      run: |
        mkdir release
        copy .\VB-Auto-Center\bin\Release\*.exe .\release\
      shell: cmd

    - name: Upload Build to Release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ./release/*
        tag: v1.0.0  # Replace with your desired version
        releaseName: "Release v1.0.0"
        draft: false
        prerelease: false
